spring.application.name=semana2

spring.datasource.url=jdbc:oracle:thin:@mibd_high
spring.datasource.username=SLOBOS
spring.datasource.password=DesarrolloFullStack.2026

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# PARA OCUPAR EL WALLET SE DEBE SUBIR LA RUTA A UNA VARIABLE DE ENTORNO
# EJEMPLO: CMD -> setx TNS_ADMIN "C:/Users/Usuario/Desktop/DuocUC/Desarrollo Fullstack 1/Spring Boot Project/ms-peliculas-database/src/main/resources/wallet"